### ISSUE TITLE
No action when switching to the same state

### ISSUE THREAD

**Issue by Tezzlicious** [Kapima-Systems/homebridge-edomoticz-ui-x#4]
Hi there,

I'm using homebridge with the homebridge-edomoticz-ui-x and homebridge-gsh plugins and have the following situation: I have some switches which respond differently when switching ON depending on the time of the day. So basically a switch is already On and I'm trying to force it to switch On again. 

I see the following happening in the homebridge log:

[1/25/2020, 6:28:59 PM] [Google Smart Home] Received EXECUTE intent
"execution": [
              {
                "command": "action.devices.commands.OnOff",
                "params": {
                  "on": true
                }

[1/25/2020, 6:28:59 PM] [Google Smart Home] [
  {
    ids: [
      'aa82f7e4bf9bc80e7eca19f14681fe4f3e7489f6d2ca152118dab1474a70c7eb'
    ],
    status: 'SUCCESS'
  }
]

But homebridge-edomoticz-ui-x  just seems to ignore the action, there is nothing incoming when I look into my domoticz log and the switch history. When I first switch it Off and back On it works. I would like it to basically ignore the current state and just execute the command.

I don't think this is normal behaviour?

**Comment by DewGew** [comment]
This repository is deprecated. Please add you issue at https://github.com/PatchworkBoy/homebridge-edomoticz
